application: hkairi-serv
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /public
  static_dir: public

- url: /.*
  script: app.app

default_expiration: "1h"

libraries:
- name: jinja2
  version: latest
